name = "Nixium Client"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6bdaefa7bb611038f9696b39f24a514b69d911490637a99fe578b369cc50114"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
