name = "Nixium Client"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a811e823d8ed8b22b62935c8b86778f2c17a2e226ee2cd6e5a1e180515b8cc35"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
