name = "Nixium Client"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adc91178460fa52f5b23fd9b29b8bb6d94d76e64ca64469f6e29a6b7a6cd5999"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
