name = "Nixium Server"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c00f6916644cc839a57c35c3e954b4d42f1b06f593b5ab534d4919d3e58b21e"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
