name = "Nixium Server"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "071527eccd6d1a2993a381c147127322d99d482abd5feab0691f5e934e35403a"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
