name = "Nixium Server"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d24586d6e48da2057dcbe2c126626db621cce597d29fde9ae13cb9d1052c61fe"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
